### ISSUE TITLE
香港永远是属于中国的！

### ISSUE THREAD

**Issue by Yangyc07** [hongkonggong/beyond-lennon-walls#5]
一群美国人和英国人的狗，笑死我了，牧羊犬。

**Comment by weathon** [comment]
有人说香港不是中国的了吗

**Comment by weathon** [comment]
笑死我了，无中生有果然还是无脑五毛厉害

**Comment by Yangyc07** [comment]
> 有人说香港不是中国的了吗
🌶️你说你🐎呢，你个🍔

**Comment by Yangyc07** [comment]
> 笑死我了，无中生有果然还是无脑五毛厉



> 笑死我了，无中生有果然还是无脑五毛厉害

牧🐑犬给👴爬

**Comment by weathon** [comment]
@Yangyc07 香港人的五大诉求你看过了吗？有哪一条是独立？没看过就乱发声。似乎只有五毛会这样不讲道理直接骂人。

**Comment by weathon** [comment]
为暴政专制说话还理直气壮了？

**Comment by weathon** [comment]
铲除共产党反华势力刻不容缓啊

**Comment by weathon** [comment]
追求自由就变成狗了？那么屈服于并且宣扬专制呢？

**Comment by Yangyc07** [comment]
> 追求自由就变成狗了？那么屈服于并且宣扬专制呢？

五大诉求不就是变相独立？
我也有五大诉求，但你能不能给我先磕个头？
暴政？
香港的废青们，只要和他们意见不合，就采用暴力的手段，用汽油烧人，被砖头砸死的老伯。
最后，我合计您祖上也是汉奸吧，这么着急帮着外国人对付中国人？

**Comment by weathon** [comment]
因为我是中华儿女不是马列子孙

**Comment by weathon** [comment]
五大诉求，
撤回条例修正案，该案没有经过合法渠道，故该诉求合理
双普选，这是《基本法》赐予的权力
独立调查委员会，这个我觉得没什么说的
释放被捕示威者，这个同样是不合法的抓捕

**Comment by weathon** [comment]
而且前几天香港区议会选举出来了，如果按照《基本法》，尊重民意有什么v错吗？赤匪

**Comment by weathon** [comment]
而且一个民主国家会这么怕“分裂”？

**Comment by weathon** [comment]
你把你的五大诉求提出来，我不是政府，所以回应不了，你去和政府提，然后再看看有多少自由地区的人支持

**Comment by weathon** [comment]
@Yangyc07

**Comment by Yangyc07** [comment]
那为什么西班牙政府要阻止加泰罗尼亚独立？直接进去抓人？有这样的民主政府吗？香港人政治本身就极不成熟，香港在回归后比英国殖民下拥有更多的民主，香港的自由度排在世界第三，请问追求的自由是什么？

**Comment by Yangyc07** [comment]
我觉得投票的结果是好事，让他们闹，越乱越好处理

**Comment by Yangyc07** [comment]
最后，你别说你是炎黄子孙好嘛？炎黄子孙先想着分裂中国？

**Comment by weathon** [comment]
苏格兰独立有政府阻拦吗？@Yangyc07

**Comment by weathon** [comment]
而且我没说过我是炎黄子孙，我说的是中华儿女

**Comment by weathon** [comment]
而且我不知道你是被大陆怎么洗脑了，一个地区要独立就一定是邪恶的？而且独立的原因不是政府？而且我不主张独立，大陆自古以来就是中国的领土，不是赤匪的

**Comment by Yangyc07** [comment]
请问白皮是中国人吗？你反正愿意当白皮的狗

**Comment by weathon** [comment]
我是不是狗还不知道，但是你就是赤匪，这有问题吗

**Comment by Yangyc07** [comment]
我说他们邪恶了？只是幼稚而已，本来就是政治斗争，你们总是想的太简单

**Comment by weathon** [comment]
政治斗争哪里比得过中共的内斗

**Comment by weathon** [comment]
@Yangyc07

**Comment by Yangyc07** [comment]
香蕉人，汉奸应该没说错

**Comment by weathon** [comment]
1，我不是香蕉人
2，汉奸因该是赤匪

**Comment by weathon** [comment]
赤匪卖了中国多少领土你知道吗

**Comment by Yangyc07** [comment]
你也配称为中国人？

**Comment by weathon** [comment]
请说明原因

**Comment by Yangyc07** [comment]
你打算分裂多少领土呢？

**Comment by weathon** [comment]
你是赤匪，不是中国人

**Comment by weathon** [comment]
香港的面积和赤匪卖出去的相比太少了

**Comment by Yangyc07** [comment]
你不是要分裂吗，还好意思说？打自己的脸？

**Comment by weathon** [comment]
而且我不主张独立，大陆自古以来就是中国的领土

**Comment by Yangyc07** [comment]
你不是要分裂吗，还好意思说？打自己的脸？

**Comment by weathon** [comment]
你这逻辑那里来的？我哪里说要分裂了

**Comment by Yangyc07** [comment]
你要把白皮引进来？

**Comment by weathon** [comment]
我没有提到过白皮，

**Comment by weathon** [comment]
我说的是你们口中所谓的“分裂国家”分裂的面积和中共买出去的相比真的太少了。你去看看中共赤匪卖了多少国土吧，中共就是一个卖国贼

**Comment by Yangyc07** [comment]
说的好像你能拿回来？

**Comment by weathon** [comment]
而且香港是在中共篡权之前被英国殖民的，后来就要回来了，蒙古独立比那还晚，为什么中共不管了？

**Comment by weathon** [comment]
@Yangyc07 蒙古拿不回来不说，那那些卖出去的土地呢？是卖出去的

**Comment by weathon** [comment]
而且中共赤匪不是很厉害的吗

**Comment by weathon** [comment]
@Yangyc07 反正我不支持独立，但是香港名义支持民主这可不是中共赤匪之前说的“一小撮”“乱港分子”

**Comment by Yangyc07** [comment]
请问你能拿回来吗？请问你支持香港分裂吗？

**Comment by weathon** [comment]
香港本来就是特别行政区，拥有很多独立治权，香港人没有要独立，只是要拿回《基本法》赋予的权利

**Comment by weathon** [comment]
再说一次，我不支持独立

**Comment by Yangyc07** [comment]
香港在回归之前就没有的权利，只有只有多的

**Comment by weathon** [comment]
我没说过我能拿回来，但是你怎么把这种“你行你上”的谬误了？我不能还不能评论了？

**Comment by Yangyc07** [comment]
那你去看看你前面的内容

**Comment by weathon** [comment]
@Yangyc07 我的观点是，我不支持独立，但我理解支持独立的行为

**Comment by weathon** [comment]
我不认为独立是错的，但是我个人立场不支持独立

**Comment by weathon** [comment]
就像你认为榴莲不好吃但是理解那些认为榴莲好吃的人

**Comment by Yangyc07** [comment]
你口口声声说赤匪，那请问你有什么好的方案呢

**Comment by weathon** [comment]
还是那句，我没方案不代表我不能评价

**Comment by weathon** [comment]
中共的人名代表大会制度其实很不错，但是执行起来根本没有达到预期效果

**Comment by Yangyc07** [comment]
我的价值观不同，我尊重，但是我也可以不接受你的

**Comment by weathon** [comment]
我现在觉得大陆的制度理想中没问题，实际上很多问题，至于问题来自制度本身还是执行方式，我倾向于后者

**Comment by Yangyc07** [comment]
肯定没执行好，这个都知道，但是我觉得是越来越好的，至少在我看来是这样

**Comment by weathon** [comment]
所以我个人希望中共可以内部优化，但是可不可能我就不知道了

**Comment by weathon** [comment]
要是活着好好的没人会要求独立

**Comment by Yangyc07** [comment]
你也要看香港的资本家啊

**Comment by weathon** [comment]
要是中共真的按照宪法和基本法执行了，那么真的不会太差

**Comment by weathon** [comment]
> 你也要看香港的资本家啊
没明白

**Comment by Yangyc07** [comment]
不说了，就这样结束这个话题吧

**Comment by Yangyc07** [comment]
在外面自信点！别总说坏话
